version: '3'

services:
  talking_station:
    build: .
    image: annieka/yandex-station-telegram-bot:latest
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30